name: QmlShaderEffect

on:
  push:
    branches:
      - QmlShaderEffect
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.2.4'
        target: 'android'
        arch: 'android_arm64-v8a'
        modules: 'qtimageformats qtshadertools'
        cache: true
    - name: Pry into dirs
      run: ls -lh && ls -lh ..
        
